### PR TITLE
major overhaul

### PR DESCRIPTION
**Pull request by vortexing**
This is the overhaul of the master branch to remove the website materials as they are now housed in the gh-pages branch.  If this is ok by everyone, then someone merge it and we'll have a clean slate to begin structuring the master branch repo the way people want it.

### CODE REVIEW

**Review by LisaMc — CHANGES_REQUESTED** [review]
Can we resurrect the Contributing.md file and add back in the reference to it in the Readme.md under "Get Involved"?  I'm not too familiar with how the gh-pages need to be structured and located, so leaving that part to @TapscottLab.  Otherwise works for me!  Thanks!

**Comment by vortexing** [comment]
I added back in the CONTRIBUTING file.  Didn't mean to delete it, but meant to copy the text of it into the readme so it shows up on the front page too.  Is that cool by you to have it in both formats @LisaMc ?

**Comment by vortexing** [comment]
FYI, this addresses Issue #4

**Comment by vortexing** [comment]
@LisaMc @TapscottLab Can one of you review this again and approve it so we can merge it and start using it?

**Review by LisaMc — APPROVED** [review]

**Comment by LisaMc** [comment]
@vortexing Let's give it a go!  Thanks for putting this together.

**Pull request merged**
